saque = 100
limite = 100

# VERIFICA SE OS DOIS OBJETOS OCUPAM A MESMA POSIÇÃO DE ESPAÇO NA MEMÓRIA
print(saque is limite)

# VERIFICA SE OS DOIS OBJETOS NÃO OCUPAM A MESMA POSIÇÃO DE ESPCAÇO NA MEMÓRIA
print(limite is not saque)